In [208]:
import pandas as pd

school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

school_data_df = pd.read_csv(school_data_to_load)
students_data_df = pd.read_csv(student_data_to_load)

student_names = students_data_df["student_name"].tolist()

students_to_fix = []

students_fixed = []


# Add each prefix and suffix to remove to a list.
prefixes_suffixes = ["Dr. ", "Mr. ","Ms. ", "Mrs. ", "Miss ", " MD", " DDS", " DVM", " PhD"]

# Iterate through the words in the "prefixes_suffixes" list and replace them with an empty space, "".
for word in prefixes_suffixes:
    students_data_df["student_name"] = students_data_df["student_name"].str.replace(word,"")


students_data_df.head(10)

# Put the cleaned students' names in another list.
student_names = students_data_df["student_name"].tolist()


# Create a new list and use it for the for loop to iterate through the list.


# Use an if statement to check the length of the name.

# If the name is greater than or equal to 3, add the name to the list.

for name in student_names:
    if len(name.split())>=3:
        students_fixed.append(name)

len(students_fixed)


school_data_complete_df = pd.merge(students_data_df, school_data_df, on="school_name")

# Get the total number of students.
student_count = school_data_complete_df["Student ID"].count()

school_count = school_data_df["school_name"].count()

total_budget = school_data_df["budget"].sum()

average_reading_score = school_data_complete_df["reading_score"].mean()

average_math_score = school_data_complete_df["math_score"].mean()

passing_math = school_data_complete_df[school_data_complete_df["math_score"] >= 70]

passing_reading = school_data_complete_df[school_data_complete_df["reading_score"] >= 70]


passing_math_count = passing_math["student_name"].count()

passing_reading_count = passing_reading["student_name"].count()

passing_math_percentage = passing_math_count / float(student_count)*100

passing_reading_percentage = passing_reading_count / float(student_count)*100



passing_math_reading = school_data_complete_df[(school_data_complete_df["math_score"] >= 70) & (school_data_complete_df["reading_score"] >= 70)]
                                                                      
passing_math_reading.head()

overall_passing_math_reading_count = passing_math_reading["student_name"].count()

overall_passing_math_reading_count

overall_passing_percentage = overall_passing_math_reading_count/student_count*100

overall_passing_percentage


#Creating summary output
district_summary_df = pd.DataFrame(
                [{"Total Schools":school_count,
                 "Total Students":student_count,
                 "Total Budget": total_budget,
                 "Average Math Score": average_math_score,
                 "Average Reading Score": average_reading_score,
                 "% Passing Math": passing_math_percentage,
                 "% Passing Reading": passing_reading_percentage,
                 "% Overall Passing": overall_passing_percentage}])

#Formatting outputs
district_summary_df["Total Students"] = district_summary_df["Total Students"].map("{:,}".format)

district_summary_df["Total Budget"] = district_summary_df["Total Budget"].map("${:,.2f}".format)

district_summary_df["Average Math Score"] = district_summary_df["Average Math Score"].map("{:.1f}".format)

district_summary_df["Average Reading Score"] = district_summary_df["Average Reading Score"].map("{:.1f}".format)

district_summary_df["% Passing Math"] = district_summary_df["% Passing Math"].map("{:.0f}".format)

district_summary_df["% Passing Reading"] = district_summary_df["% Passing Reading"].map("{:.0f}".format)

district_summary_df["% Overall Passing"] = district_summary_df["% Overall Passing"].map("{:.0f}".format)


#setting order of columns
new_column_order = [
    "Total Schools",
    "Total Students",
    "Total Budget",
    "Average Math Score",
    "Average Reading Score",
    "% Passing Math",
    "% Passing Reading",
    "% Overall Passing",]

district_summary_df = district_summary_df[new_column_order]

per_school_types = school_data_df.set_index("school_name")["type"]

df = pd.DataFrame(per_school_types)


#This does the
per_school_counts = school_data_df.set_index(["school_name"])["size"]

per_school_counts

#same as this
per_school_counts2 = school_data_complete_df["school_name"].value_counts()

per_school_counts2



#Find the Budget per Student per school

per_school_budget = school_data_df.set_index(["school_name"])["budget"]

per_school_capita = per_school_budget / per_school_counts

per_school_capita





#Find average rading and math scores per school
# Calculate the math scores.
student_school_math = school_data_complete_df.groupby(["school_name"]).mean()["math_score"]


per_school_reading = school_data_complete_df.groupby(["school_name"]).mean()["reading_score"]


per_school_math = school_data_complete_df.groupby(["school_name"]).mean()["math_score"]


#Calculate passing scores by creating filtered DataFrame

per_school_passing_math = school_data_complete_df[(school_data_complete_df["math_score"] >= 70)]

per_school_passing_reading = school_data_complete_df[(school_data_complete_df["reading_score"] >= 70)]


# Calculate the number of students passing math and passing reading by school.
per_school_passing_math = per_school_passing_math.groupby(["school_name"]).count()["student_name"]

per_school_passing_reading = per_school_passing_reading.groupby(["school_name"]).count()["student_name"]


# Calculate the percentage of passing math and reading scores per school.
per_school_passing_math = per_school_passing_math / per_school_counts *100

per_school_passing_reading = per_school_passing_reading / per_school_counts *100

per_school_passing_math_reading = school_data_complete_df[(school_data_complete_df["math_score"] >= 70)&(school_data_complete_df["reading_score"] >= 70)]

per_school_passing_math_reading = per_school_passing_math_reading.groupby(["school_name"]).count()["student_name"]

per_school_passing_math_reading= per_school_passing_math_reading / per_school_counts*100

per_school_passing_math_reading


per_school_summary_df = pd.DataFrame(
                {"School Types":per_school_types,
                 "Total Students":student_count,
                 "Total School Budget": per_school_budget,
                 "Per Student Budget": per_school_capita,
                 "Average Math Score": per_school_math,
                 "Average Reading Score": per_school_reading,
                 "% Passing Math": per_school_passing_math,
                 "% Passing Reading": per_school_passing_reading,
                 "% Overall Passing": per_school_passing_math_reading})

# Reorder the columns
new_column_order = ["School Types", "Total Students", "Total School Budget", "Per Student Budget", 
                    "Average Math Score", "Average Reading Score", "% Passing Math", 
                    "% Passing Reading","% Overall Passing"]

# Assign district summary df the new column order.
per_school_summary = per_school_summary_df[new_column_order]

#Formatting per_school_summary
per_school_summary_df["Total Students"] = per_school_summary_df["Total Students"].map("{:,}".format)
per_school_summary_df["Total School Budget"] = per_school_summary_df["Total School Budget"].map("${:,.2f}".format)
per_school_summary_df["Per Student Budget"] = per_school_summary_df["Per Student Budget"].map("${:,.2f}".format)
per_school_summary_df["Average Math Score"] = per_school_summary_df["Average Math Score"].map("{:.1f}".format)
per_school_summary_df["Average Reading Score"] = per_school_summary_df["Average Reading Score"].map("{:.1f}".format)
per_school_summary_df["% Passing Math"] = per_school_summary_df["% Passing Math"].map("{:.1f}".format)
per_school_summary_df["% Passing Reading"] = per_school_summary_df["% Passing Reading"].map("{:.1f}".format)
per_school_summary_df[ "% Overall Passing"] = per_school_summary_df[ "% Overall Passing"].map("{:.1f}".format)




top_schools = per_school_summary_df.sort_values(["% Overall Passing"], ascending=False)

top_schools.head()

bottom_schools = per_school_summary_df.sort_values(["% Overall Passing"])

bottom_schools.head()


school_data_complete_df.head()


#Breakdown by grade

ninth_graders = school_data_complete_df[(school_data_complete_df)["grade"]=="9th"]
tenth_graders = school_data_complete_df[(school_data_complete_df)["grade"]=="10th"]
eleventh_graders = school_data_complete_df[(school_data_complete_df)["grade"]=="11th"]
twelfth_graders = school_data_complete_df[(school_data_complete_df)["grade"]=="12th"]




#Breakdown of average MATH by grade
ninth_grade_math_scores = ninth_graders.groupby(["school_name"]).mean()["math_score"]
tenth_grade_math_scores = tenth_graders.groupby(["school_name"]).mean()["math_score"]
eleventh_grade_math_scores = eleventh_graders.groupby(["school_name"]).mean()["math_score"]
twelfth_grade_math_scores = twelfth_graders.groupby(["school_name"]).mean()["math_score"]

## Adding to dataframe
math_scores_by_grade = pd.DataFrame(
                {"9th":ninth_grade_math_scores,
                 "10th":tenth_grade_math_scores,
                 "11th": eleventh_grade_math_scores,
                 "12th": twelfth_grade_math_scores,})
### Formatting
math_scores_by_grade["9th"] = math_scores_by_grade["9th"].map("{:.1f}".format)
math_scores_by_grade["10th"] = math_scores_by_grade["10th"].map("{:.1f}".format) 
math_scores_by_grade["11th"] = math_scores_by_grade["11th"].map("{:.1f}".format) 
math_scores_by_grade["12th"] = math_scores_by_grade["12th"].map("{:.1f}".format) 

#### Column Order
math_scores_by_grade = math_scores_by_grade[["9th","10th","11th","12th"]]

##### Remove 1st column header
math_scores_by_grade.index.name = None



# Breakdown of average READING by grade
ninth_grade_reading_scores = ninth_graders.groupby(["school_name"]).mean()["reading_score"]
tenth_grade_reading_scores = tenth_graders.groupby(["school_name"]).mean()["reading_score"]
eleventh_grade_reading_scores = eleventh_graders.groupby(["school_name"]).mean()["reading_score"]
twelfth_grade_reading_scores = twelfth_graders.groupby(["school_name"]).mean()["reading_score"]

## Adding to dataframe
reading_scores_by_grade = pd.DataFrame(
                {"9th":ninth_grade_reading_scores,
                 "10th":tenth_grade_reading_scores,
                 "11th": eleventh_grade_reading_scores,
                 "12th": twelfth_grade_reading_scores,})
### Formatting
reading_scores_by_grade["9th"] = reading_scores_by_grade["9th"].map("{:.1f}".format)
reading_scores_by_grade["10th"] = reading_scores_by_grade["10th"].map("{:.1f}".format) 
reading_scores_by_grade["11th"] = reading_scores_by_grade["11th"].map("{:.1f}".format) 
reading_scores_by_grade["12th"] = reading_scores_by_grade["12th"].map("{:.1f}".format)

#### Column Order
reading_scores_by_grade = reading_scores_by_grade[["9th","10th","11th","12th"]]

##### Remove 1st column header
reading_scores_by_grade.index.name = None

math_scores_by_grade

C:\Users\Chapm\.conda\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: The default value of regex will change from True to False in a future version.

                        9th  10th  11th  12th
Bailey High School     77.1  77.0  77.5  76.5
Cabrera High School    83.1  83.2  82.8  83.3
Figueroa High School   76.4  76.5  76.9  77.2
Ford High School       77.4  77.7  76.9  76.2
Griffin High School    82.0  84.2  83.8  83.4
Hernandez High School  77.4  77.3  77.1  77.2
Holden High School     83.8  83.4  85.0  82.9
Huang High School      77.0  75.9  76.4  77.2
Johnson High School    77.2  76.7  77.5  76.9
Pena High School       83.6  83.4  84.3  84.1
Rodriguez High School  76.9  76.6  76.4  77.7
Shelton High School    83.4  82.9  83.4  83.8
Thomas High School     83.6  83.1  83.5  83.5
Wilson High School     83.1  83.7  83.2  83.0
Wright High School     83.3  84.0  83.8  83.6

In [180]:
class Dog:
    def __init__(self, name, color, sound):
        self.name = name
        self.color = color
        self.sound = sound

    def bark(self):
        return self.sound + ' ' + self.sound
    
first_dog = Dog('Fido', 'brown', 'woof!')

second_dog = Dog('Lady', 'blonde', 'arf!')

print(    first_dog.name)
print(first_dog.color)
second_dog.bark()

Fido
brown

'arf! arf!'