In [86]:
import pandas as pd

school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

school_data_df = pd.read_csv(school_data_to_load)
students_data_df = pd.read_csv(student_data_to_load)

student_names = students_data_df["student_name"].tolist()

students_to_fix = []

students_fixed = []


# Add each prefix and suffix to remove to a list.
prefixes_suffixes = ["Dr. ", "Mr. ","Ms. ", "Mrs. ", "Miss ", " MD", " DDS", " DVM", " PhD"]

# Iterate through the words in the "prefixes_suffixes" list and replace them with an empty space, "".
for word in prefixes_suffixes:
    students_data_df["student_name"] = students_data_df["student_name"].str.replace(word,"")


students_data_df.head(10)

# Put the cleaned students' names in another list.
student_names = students_data_df["student_name"].tolist()


# Create a new list and use it for the for loop to iterate through the list.


# Use an if statement to check the length of the name.

# If the name is greater than or equal to 3, add the name to the list.

for name in student_names:
    if len(name.split())>=3:
        students_fixed.append(name)

len(students_fixed)


school_data_complete_df = pd.merge(students_data_df, school_data_df, on="school_name")

# Get the total number of students.
student_count = school_data_complete_df["Student ID"].count()

school_count = school_data_df["school_name"].count()

total_budget = school_data_df["budget"].sum()

average_reading_score = school_data_complete_df["reading_score"].mean()

average_math_score = school_data_complete_df["math_score"].mean()

passing_math = school_data_complete_df[school_data_complete_df["math_score"] >= 70]

passing_reading = school_data_complete_df[school_data_complete_df["reading_score"] >= 70]

passing_math_count = passing_math["student_name"].count()

passing_reading_count = passing_reading["student_name"].count()

passing_math_percentage = passing_math_count / float(student_count)*100

passing_reading_percentage = passing_reading_count / float(student_count)*100



passing_math_reading = school_data_complete_df[(school_data_complete_df["math_score"] >= 70) & (school_data_complete_df["reading_score"] >= 70)]
                                                                      
passing_math_reading.head()

overall_passing_math_reading_count = passing_math_reading["student_name"].count()

overall_passing_math_reading_count

overall_passing_percentage = overall_passing_math_reading_count/student_count*100

overall_passing_percentage


#Creating summary output
district_summary_df = pd.DataFrame(
                [{"Total Schools":school_count,
                 "Total Students":student_count,
                 "Total Budget": total_budget,
                 "Average Math Score": average_math_score,
                 "Average Reading Score": average_reading_score,
                 "% Passing Math": passing_math_percentage,
                 "% Passing Reading": passing_reading_percentage,
                 "% Overall Passing": overall_passing_percentage}])

#Formatting outputs
district_summary_df["Total Students"] = district_summary_df["Total Students"].map("{:,}".format)

district_summary_df["Total Budget"] = district_summary_df["Total Budget"].map("${:,.2f}".format)

district_summary_df["Average Math Score"] = district_summary_df["Average Math Score"].map("{:.1f}".format)

district_summary_df["Average Reading Score"] = district_summary_df["Average Reading Score"].map("{:.1f}".format)

district_summary_df["% Passing Math"] = district_summary_df["% Passing Math"].map("{:.0f}".format)

district_summary_df["% Passing Reading"] = district_summary_df["% Passing Reading"].map("{:.0f}".format)

district_summary_df["% Overall Passing"] = district_summary_df["% Overall Passing"].map("{:.0f}".format)


#setting order of columns
new_column_order = [
    "Total Schools",
    "Total Students",
    "Total Budget",
    "Average Math Score",
    "Average Reading Score",
    "% Passing Math",
    "% Passing Reading",
    "% Overall Passing",]

district_summary_df = district_summary_df[new_column_order]

district_summary_df

C:\Users\Chapm\.conda\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: The default value of regex will change from True to False in a future version.

,Total Schools,Total Students,Total Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
0,15,"39,170","$24,649,428.00",79.0,81.9,75,86,65

92
85
87
98

0    B
1    C
2    B
3    D
dtype: object