In [149]:
import pandas as pd

school_data_to_load = "Resources/schools_complete.csv"
student_data_to_load = "Resources/students_complete.csv"

school_data_df = pd.read_csv(school_data_to_load)
students_data_df = pd.read_csv(student_data_to_load)

student_names = students_data_df["student_name"].tolist()

students_to_fix = []

students_fixed = []


# Add each prefix and suffix to remove to a list.
prefixes_suffixes = ["Dr. ", "Mr. ","Ms. ", "Mrs. ", "Miss ", " MD", " DDS", " DVM", " PhD"]

# Iterate through the words in the "prefixes_suffixes" list and replace them with an empty space, "".
for word in prefixes_suffixes:
    students_data_df["student_name"] = students_data_df["student_name"].str.replace(word,"")


students_data_df.head(10)

# Put the cleaned students' names in another list.
student_names = students_data_df["student_name"].tolist()


# Create a new list and use it for the for loop to iterate through the list.


# Use an if statement to check the length of the name.

# If the name is greater than or equal to 3, add the name to the list.

for name in student_names:
    if len(name.split())>=3:
        students_fixed.append(name)

len(students_fixed)


school_data_complete_df = pd.merge(students_data_df, school_data_df, on="school_name")

# Get the total number of students.
student_count = school_data_complete_df["Student ID"].count()

school_count = school_data_df["school_name"].count()

total_budget = school_data_df["budget"].sum()

average_reading_score = school_data_complete_df["reading_score"].mean()

average_math_score = school_data_complete_df["math_score"].mean()

passing_math = school_data_complete_df[school_data_complete_df["math_score"] >= 70]

passing_reading = school_data_complete_df[school_data_complete_df["reading_score"] >= 70]


passing_math_count = passing_math["student_name"].count()

passing_reading_count = passing_reading["student_name"].count()

passing_math_percentage = passing_math_count / float(student_count)*100

passing_reading_percentage = passing_reading_count / float(student_count)*100



passing_math_reading = school_data_complete_df[(school_data_complete_df["math_score"] >= 70) & (school_data_complete_df["reading_score"] >= 70)]
                                                                      
passing_math_reading.head()

overall_passing_math_reading_count = passing_math_reading["student_name"].count()

overall_passing_math_reading_count

overall_passing_percentage = overall_passing_math_reading_count/student_count*100

overall_passing_percentage


#Creating summary output
district_summary_df = pd.DataFrame(
                [{"Total Schools":school_count,
                 "Total Students":student_count,
                 "Total Budget": total_budget,
                 "Average Math Score": average_math_score,
                 "Average Reading Score": average_reading_score,
                 "% Passing Math": passing_math_percentage,
                 "% Passing Reading": passing_reading_percentage,
                 "% Overall Passing": overall_passing_percentage}])

#Formatting outputs
district_summary_df["Total Students"] = district_summary_df["Total Students"].map("{:,}".format)

district_summary_df["Total Budget"] = district_summary_df["Total Budget"].map("${:,.2f}".format)

district_summary_df["Average Math Score"] = district_summary_df["Average Math Score"].map("{:.1f}".format)

district_summary_df["Average Reading Score"] = district_summary_df["Average Reading Score"].map("{:.1f}".format)

district_summary_df["% Passing Math"] = district_summary_df["% Passing Math"].map("{:.0f}".format)

district_summary_df["% Passing Reading"] = district_summary_df["% Passing Reading"].map("{:.0f}".format)

district_summary_df["% Overall Passing"] = district_summary_df["% Overall Passing"].map("{:.0f}".format)


#setting order of columns
new_column_order = [
    "Total Schools",
    "Total Students",
    "Total Budget",
    "Average Math Score",
    "Average Reading Score",
    "% Passing Math",
    "% Passing Reading",
    "% Overall Passing",]

district_summary_df = district_summary_df[new_column_order]

per_school_types = school_data_df.set_index("school_name")["type"]

df = pd.DataFrame(per_school_types)


#This does the
per_school_counts = school_data_df.set_index(["school_name"])["size"]

per_school_counts

#same as this
per_school_counts2 = school_data_complete_df["school_name"].value_counts()

per_school_counts2



#Find the Budget per Student per school

per_school_budget = school_data_df.set_index(["school_name"])["budget"]

per_school_capita = per_school_budget / per_school_counts

per_school_capita





#Find average rading and math scores per school
# Calculate the math scores.
student_school_math = school_data_complete_df.groupby(["school_name"]).mean()["math_score"]

student_school_math

student_school_reading = school_data_complete_df.groupby(["school_name"]).mean()["reading_score"]

student_school_reading


#Calculate passing scores by creating filtered DataFrame

per_school_passing_math = school_data_complete_df[(school_data_complete_df["math_score"] >= 70)]

per_school_passing_reading = school_data_complete_df[(school_data_complete_df["reading_score"] >= 70)]


# Calculate the number of students passing math and passing reading by school.
per_school_passing_math = per_school_passing_math.groupby(["school_name"]).count()["student_name"]

per_school_passing_reading = per_school_passing_reading.groupby(["school_name"]).count()["student_name"]


# Calculate the percentage of passing math and reading scores per school.
per_school_passing_math = per_school_passing_math / per_school_counts *100

per_school_passing_reading = per_school_passing_reading / per_school_counts *100

per_school_passing_math_reading = school_data_complete_df[(school_data_complete_df["math_score"] >= 70)&(school_data_complete_df["reading_score"] >= 70)]


per_school_passing_math_reading = per_school_passing_math_reading.groupby(["school_name"]).count()["student_name"]


per_school_passing_math_reading= per_school_passing_math_reading / per_school_counts*100

per_school_passing_math_reading


per_school_summary_df = pd.DataFrame(
                {"School Types":per_school_types,
                 "Total Students":student_count,
                 "Total Budget": per_school_budget,
                 "Per Student Budget": per_school_capita,
                 "Average Math Score": per_school_passing_math,
                 "Average Reading Score": per_school_passing_reading,
                 "% Passing Math": per_school_passing_math,
                 "% Passing Reading": per_school_passing_reading,
                 "% Overall Passing": overall_passing_percentage})

per_school_summary_df["Total Students"] = per_school_summary_df["Total Students"].map("{:,}".format)
per_school_summary_df["Total Budget"] = per_school_summary_df["Total Budget"].map("${:,.2f}".format)
per_school_summary_df["Per Student Budget"] = per_school_summary_df["Per Student Budget"].map("${:,.2f}".format)
per_school_summary_df["Average Math Score"] = per_school_summary_df["Average Math Score"].map("{:.1f}".format)
per_school_summary_df["Average Reading Score"] = per_school_summary_df["Average Reading Score"].map("{:.1f}".format)
per_school_summary_df["% Passing Math"] = per_school_summary_df["% Passing Math"].map("{:.1f}".format)
per_school_summary_df["% Passing Reading"] = per_school_summary_df["% Passing Reading"].map("{:.1f}".format)
per_school_summary_df[ "% Overall Passing"] = per_school_summary_df[ "% Overall Passing"].map("{:.1f}".format)


per_school_summary_df

C:\Users\Chapm\.conda\envs\PythonData\lib\site-packages\ipykernel_launcher.py:21: FutureWarning: The default value of regex will change from True to False in a future version.

,School Types,Total Students,Total Budget,Per Student Budget,Average Math Score,Average Reading Score,% Passing Math,% Passing Reading,% Overall Passing
school_name,,,,,,,,,
Bailey High School,District,"39,170","$3,124,928.00",$628.00,66.7,81.9,66.7,81.9,65.2
Cabrera High School,Charter,"39,170","$1,081,356.00",$582.00,94.1,97.0,94.1,97.0,65.2
Figueroa High School,District,"39,170","$1,884,411.00",$639.00,66.0,80.7,66.0,80.7,65.2
Ford High School,District,"39,170","$1,763,916.00",$644.00,68.3,79.3,68.3,79.3,65.2
Griffin High School,Charter,"39,170","$917,500.00",$625.00,93.4,97.1,93.4,97.1,65.2
Hernandez High School,District,"39,170","$3,022,020.00",$652.00,66.8,80.9,66.8,80.9,65.2
Holden High School,Charter,"39,170","$248,087.00",$581.00,92.5,96.3,92.5,96.3,65.2
Huang High School,District,"39,170","$1,910,635.00",$655.00,65.7,81.3,65.7,81.3,65.2
Johnson High School,District,"39,170","$3,094,650.00",$650.00,66.1,81.2,66.1,81.2,65.2
Pena High School,Charter,"39,170","$585,858.00",$609.00,94.6,95.9,94.6,95.9,65.2
Rodriguez High School,District,"39,170","$2,547,363.00",$637.00,66.4,80.2,66.4,80.2,65.2
Shelton High School,Charter,"39,170","$1,056,600.00",$600.00,93.9,95.9,93.9,95.9,65.2
Thomas High School,Charter,"39,170","$1,043,130.00",$638.00,93.3,97.3,93.3,97.3,65.2
Wilson High School,Charter,"39,170","$1,319,574.00",$578.00,93.9,96.5,93.9,96.5,65.2
Wright High School,Charter,"39,170","$1,049,400.00",$583.00,93.3,96.6,93.3,96.6,65.2

0    B
1    C
2    B
3    D
dtype: object